src/objects/Builder_Edge_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Builder Edge Setting</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProjectTaskService__e.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OrgId__c</fullName>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Self__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Self</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>ProjectTaskService</label>
    <pluralLabel>ProjectTaskServices</pluralLabel>
</CustomObject>

src/classes/ProjectTaskServiceTiggerTest.cls
/*************************************************************************************************
    Class Name  : ProjectTaskServiceTiggerTest 
    Description : ProjectTaskServiceTigger Test class
    Date        : 6 feb 2018.
    Version     : 1.0 - Created
    Author      : Pradip Mohite.
*************************************************************************************************/
@isTest
public class ProjectTaskServiceTiggerTest {

    @isTest static void InsertAndUpdateProject() {
        Builder_Edge_Setting__c setting = new Builder_Edge_Setting__c();
        setting.Name = 'PlatformEventPublish';
        setting.Value__c = 'True';
        insert setting;
        Project__c newProject = new Project__c();
        newProject.Name = 'Test';
        newProject.Start_Date__c = date.today();
        newProject.End_Date__c = date.today();
        insert newProject;        
        system.assert(newProject.id != null);
        
        newProject.Name = 'Test 1';
        update newProject;  
        
    }
    
    @isTest static void InsertAndUpdateProjectTask() {
        Builder_Edge_Setting__c setting = new Builder_Edge_Setting__c();
        setting.Name = 'PlatformEventPublish';
        setting.Value__c = 'True';
        insert setting;
        Project__c newProject = new Project__c();
        newProject.Name = 'Test';
        newProject.Start_Date__c = date.today();
        newProject.End_Date__c = date.today();
        insert newProject;        
        system.assert(newProject.id != null);
        
        Project_Task__c tRec = new Project_Task__c();
        tRec.Name = 'Test';
        tRec.Start_Date__c = date.today();
        tRec.End_Date__c = date.today();
        tRec.Project__c = newProject.id;
        insert tRec;
        
        tRec.Name = 'Test 1';
        update tRec;  
        
    }
    
    @isTest static void publishEvent(){
        Builder_Edge_Setting__c setting = new Builder_Edge_Setting__c();
        setting.Name = 'PlatformEventPublish';
        setting.Value__c = 'True';
        insert setting;
        Project__c newProject = new Project__c();
        newProject.Name = 'Test';
        newProject.Start_Date__c = date.today();
        newProject.End_Date__c = date.today();
        insert newProject;        
        system.assert(newProject.id != null);
        
        Project_Task__c tRec = new Project_Task__c();
        tRec.Name = 'Test';
        tRec.Start_Date__c = date.today();
        tRec.End_Date__c = date.today();
        tRec.Project__c = newProject.id;
        insert tRec;
        projectTaskClass ptClassObj = new projectTaskClass();
        ptClassObj.ProjectTasks = new List<Project_Task__c>();
        ptClassObj.ProjectTasks.add(tRec);
        ptClassObj.Projects = new List<Project__c>();
        ptClassObj.Projects.add(newProject);
        List<ProjectTaskService__e> ProjectTaskEvent = new List<ProjectTaskService__e>();
        ProjectTaskEvent.add(new ProjectTaskService__e(Data__c=JSON.serialize(ptClassObj),User__c = UserInfo.getUserId(),OrgId__c=UserInfo.getOrganizationId(),Self__c=false,Action__c='update' ));
    	List<Database.SaveResult> results = EventBus.publish(ProjectTaskEvent);
    	for (Database.SaveResult sr : results) {
                if (sr.isSuccess()) {
                    System.debug('Successfully published event.');
                } else {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('Error returned: ' +
                                     err.getStatusCode() +
                                     ' - ' +
                                     err.getMessage());
                    }
                }       
        	}        
    }
    public class projectTaskClass{
		List<Project__c> Projects{get;set;}
		List<Project_Task__c> ProjectTasks{get;set;}
	}
}