src/objects/Builder_Edge_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Builder Edge Setting</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProjectTaskService__e.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Self__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Self</label>
        <type>Checkbox</type>
    </fields>
    <label>ProjectTaskService</label>
    <pluralLabel>ProjectTaskServices</pluralLabel>
</CustomObject>

src/classes/ProjectTaskServiceTiggerHandler.cls
/*************************************************************************************************
    Class Name  : ProjectTaskServiceTiggerHandler 
    Description : Handler use to create or update project and task record
    Date        : 2 feb 2018.
    Version     : 1.0 - Created
    Author      : Pradip Mohite.
*************************************************************************************************/
public class ProjectTaskServiceTiggerHandler {
    
    /*************************************************************************************************
        Method Name  : upsertProjectTask
        Description : This method use to subscribe platform event and update project and project task record.
    *************************************************************************************************/
    public static void upsertProjectTask(List<ProjectTaskService__e> projectTaskServices){
        List<Project_Task__c> tasks= new List<Project_Task__c>();
        List<Project__c> projects= new List<Project__c>();
        system.debug('projectTaskServices==>'+projectTaskServices);
        Builder_Edge_Setting__c PlatformEventSetting = Builder_Edge_Setting__c.getValues('PlatformEventPublish');
        System.debug('PlatformEventSetting'+PlatformEventSetting);
        for (ProjectTaskService__e projectTask :projectTaskServices) { 
            if(!projectTask.Self__c && projectTask.Data__c != null){
                string data = projectTask.Data__c;
                projectTaskClass projectTaskClassObj = (projectTaskClass) JSON.deserialize(data, projectTaskClass.class);       
                if(projectTaskClassObj != null && projectTaskClassObj.ProjectTasks != null && projectTaskClassObj.ProjectTasks.size() > 0){
                    for(Project_Task__c ptEvent :projectTaskClassObj.ProjectTasks){
                        tasks.add(ptEvent); 
                    }  
                }
                if(projectTaskClassObj != null && projectTaskClassObj.Projects != null && projectTaskClassObj.Projects.size() > 0){
                    for(Project__c pEvent :projectTaskClassObj.Projects){
                        projects.add(pEvent); 
                    }  
                }
            }		          
        }
        if(tasks != null && tasks.size() > 0){
            if(PlatformEventSetting != null){
               PlatformEventSetting.Value__c = 'False';
            	update PlatformEventSetting; 
            }         
            QueryHandler.upsertRecordsWithoutAccessCheck(tasks,true);
            
        }
        if(projects != null && projects.size() > 0){
            if(PlatformEventSetting != null){
               PlatformEventSetting.Value__c = 'False';
            	update PlatformEventSetting; 
            }
            QueryHandler.upsertRecordsWithoutAccessCheck(projects,true);
        }
	}
    
	public class projectTaskClass{
		List<Project__c> Projects{get;set;}
		List<Project_Task__c> ProjectTasks{get;set;}
	}
}