src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Completion_Percentage__c</fullName>
        <label>Completion Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <label>External Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Completion_Percentage__c</fullName>
        <label>Completion Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <label>External Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectService.cls
/*************************************************************************************************
    Class Name  : ProjectService 
    Description : Controller use to expose product object rest service
    Date        : 31 Jan 2018.
    Version     : 1.0 - Created
    Author      : Pradip Mohite.
*************************************************************************************************/
@RestResource(urlMapping='/ProductSerivce/*')
global with sharing class ProjectService {
    
    /***********************************************************************************************
        Method Name : upsertProject
        Description : GET method to use fetch project records. 
        Date        : 31 Jan 2018.
        Author      : Pradip Mohite.
    ************************************************************************************************/
    @HttpGet
    global static List<Project__c> getProjects() {
        List<Project__c> projects = QueryHandler.getQueryData('Project__c', new List<string>{'Completion_Percentage__c','CreatedById','CreatedDate','Description__c','End_Date__c','External_Id__c','LastModifiedById','LastModifiedDate','Name','OwnerId','Start_Date__c','Status__c'}, null, '(SELECT Completion_Percentage__c,CreatedById,CreatedDate,Description__c,End_Date__c,External_Id__c,Id,LastModifiedById,LastModifiedDate,Name,Project__c,Start_Date__c,Status__c FROM Project_Tasks__r)');
        return projects ;
    }
    
    /***********************************************************************************************
        Method Name : deleteProject
        Description : POST method to use insert or update project record. 
        Date        : 31 Jan 2018.
        Author      : Pradip Mohite.
    ************************************************************************************************/
    @HttpDelete
    global static void deleteProject() {
        RestRequest request = RestContext.request;
        String projectId = request.requestURI.substring(
            request.requestURI.lastIndexOf('/')+1);
        Project__c projectObj = [SELECT Id FROM Project__c WHERE Id = :projectId];
        delete projectObj;
    } 
}