src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectServiceTest.cls
/*************************************************************************************************
    Class Name  : ProjectServiceTest 
    Description : ProjectService Test class
    Date        : 6 feb 2018.
    Version     : 1.0 - Created
    Author      : Pradip Mohite.
*************************************************************************************************/
@isTest
public class ProjectServiceTest {
	static testMethod void  getProjectTest(){
       	PlatformEventSetting__c setting = new PlatformEventSetting__c();
        setting.Name = 'ProjectTaskService';
        setting.Publish__c = true;
        insert setting;
        Project__c newProject = new Project__c();
        newProject.Name = 'Test';
        newProject.Start_Date__c = date.today();
        newProject.End_Date__c = date.today();
        insert newProject;        
        system.assert(newProject.id != null);
        
        Project_Task__c tRec = new Project_Task__c();
        tRec.Name = 'Test';
        tRec.Start_Date__c = date.today();
        tRec.End_Date__c = date.today();
        tRec.Project__c = newProject.id;
        insert tRec;
       	Test.startTest();    
       	RestRequest req = new RestRequest(); 
       	RestResponse res = new RestResponse();
    
        req.requestURI = '/services/apexrest/ProductService'; 
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        ProjectService.getProjects();
        Test.stopTest();

   }
}